title: BitShares Blockchain Foundation
url: "http://www.bitshares.foundation"
baseurl: ""
markdown: kramdown
tracking_id: UA-102444300-1

sass:
 style: compressed
 sass_dir: _sass

collections:
 escrows:
  output: true
  permalink: /worker/escrow/:name
 budgets:
  output: true
  permalink: /worker/budget/:name
 announcements:
  output: true
  permalink: /:collection/:name

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
